
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "My AI Productivity PWA", // アプリのタイトル
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
        <body className={`${inter.className} bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-gray-100`}>
        <div className="flex flex-col min-h-screen">
            {/* ヘッダー */}
            <header className="bg-white dark:bg-gray-800 shadow-md sticky top-0 z-10">
                <nav className="container mx-auto px-6 py-3">
                    <div className="flex justify-between items-center">
                        <h1 className="text-xl font-bold text-blue-600 dark:text-blue-400">
                            AI PWA
                        </h1>
                        <div>
                            {/* ここにログインボタンなどを後で追加します */}
                            <button className="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600">
                                Login
                            </button>
                        </div>
                    </div>
                </nav>
            </header>

            {/* メインコンテンツエリア */}
            <main className="flex-1 container mx-auto p-6">
                {children} {/* ← ここに各ページの内容が表示されます */}
            </main>

            {/* フッター */}
            <footer className="bg-white dark:bg-gray-800 mt-8 py-4">
                <div className="container mx-auto px-6 text-center text-gray-500">
                    <p>© 2024 Your Name. All Rights Reserved.</p>
                </div>
            </footer>
        </div>
        </body>
        </html>
    );
}